Repository FintoryApp/fintory_BE, pull requests merged in 2025-09, with the labels that each got.

#40 [FIX] stock_trading 오류 수정
  infra/src/main/java/com/fintory/infra/domain/portfolio/properties/EosProperties.java
  infra/src/main/java/com/fintory/infra/domain/portfolio/repository/StockTransactionRepository.java
  infra/src/main/java/com/fintory/infra/domain/portfolio/serviceImpl/PortfolioServiceImpl.java
  infra/src/main/java/com/fintory/infra/domain/trading/ExchangeRateServiceImpl.java
Labels: bug

#41 fix: 증권 api 배포환경에 환경변수 추가
  .github/workflows/deploy.yml
  app-child/src/main/resources/application-deploy.yml
Labels: chore

#44 [FEAT] 계좌 초기화 api
  app-child/src/main/java/com/fintory/child/domain/account/controller/AccountController.java
  app-child/src/main/resources/application-local.yml
  auth/src/main/java/com/fintory/auth/service/AuthService.java
  common/src/main/java/com/fintory/common/exception/DomainErrorCode.java
  common/src/main/java/com/fintory/common/exception/DomainException.java
  domain/src/main/java/com/fintory/domain/account/model/Account.java
  domain/src/main/java/com/fintory/domain/account/model/DepositTransaction.java
  domain/src/main/java/com/fintory/domain/account/model/DepositTransactionType.java
  domain/src/main/java/com/fintory/domain/account/service/AccountService.java
  domain/src/main/java/com/fintory/domain/badge/model/Badge.java
  domain/src/main/java/com/fintory/domain/child/model/Child.java
  domain/src/main/java/com/fintory/domain/financialword/model/FinancialWord.java
  domain/src/main/java/com/fintory/domain/mapping/MyQuiz.java
  domain/src/main/java/com/fintory/domain/mapping/UserBadge.java
  domain/src/main/java/com/fintory/domain/parent/model/Parent.java
  domain/src/main/java/com/fintory/domain/point/model/Point.java
  domain/src/main/java/com/fintory/domain/point/model/PointTransaction.java
  domain/src/main/java/com/fintory/domain/point/model/PointTransactionSource.java
  domain/src/main/java/com/fintory/domain/point/model/PointTransactionType.java
  domain/src/main/java/com/fintory/domain/portfolio/model/OwnedStock.java
  domain/src/main/java/com/fintory/domain/portfolio/model/StockTransaction.java
  domain/src/main/java/com/fintory/domain/quiz/model/DailyQuizAttempt.java
  domain/src/main/java/com/fintory/domain/quiz/model/Quiz.java
  infra/src/main/java/com/fintory/infra/domain/account/repository/AccountRepository.java
  infra/src/main/java/com/fintory/infra/domain/account/serviceImpl/AccountServiceImpl.java
  infra/src/main/java/com/fintory/infra/domain/trading/TradingServiceImpl.java
Labels: chore, feature

#46 [FEAT] 계좌 내역, 보유 현금 반환 api
  app-child/src/main/java/com/fintory/child/domain/account/controller/AccountController.java
  app-child/src/main/java/com/fintory/child/domain/account/controller/AccountControllerImpl.java
  domain/src/main/java/com/fintory/domain/account/dto/response/DepositTransactionResponse.java
  domain/src/main/java/com/fintory/domain/account/dto/response/TotalAssetsResponse.java
  domain/src/main/java/com/fintory/domain/account/model/DepositTransaction.java
  domain/src/main/java/com/fintory/domain/account/service/AccountService.java
  infra/src/main/java/com/fintory/infra/config/CommonConfig.java
  infra/src/main/java/com/fintory/infra/domain/account/repository/AccountRepository.java
  infra/src/main/java/com/fintory/infra/domain/account/repository/DepositTransactionRepository.java
  infra/src/main/java/com/fintory/infra/domain/account/serviceImpl/AccountServiceImpl.java
Labels: feature

#52 [FIX] 부모앱 삭제
  .github/workflows/deploy.yml
  app-child/src/main/java/com/fintory/child/domain/news/controller/NewsControllerImpl.java
  app-child/src/main/java/com/fintory/child/domain/portfolio/controller/PortfolioControllerImpl.java
  app-parent/Dockerfile
  app-parent/build.gradle
  app-parent/src/main/java/com/fintory/parent/ParentApplication.java
  app-parent/src/main/java/com/fintory/parent/exceptionhandler/DomainExceptionHandler.java
  app-parent/src/main/java/com/fintory/parent/exceptionhandler/GlobalExceptionHandler.java
  app-parent/src/main/resources/application-deploy.yml
  app-parent/src/main/resources/application-local.yml
  app-parent/src/main/resources/application.yml
  auth/src/main/java/com/fintory/auth/config/SecurityConfig.java
  auth/src/main/java/com/fintory/auth/controller/AuthControllerImpl.java
  auth/src/main/java/com/fintory/auth/controller/ChildAuthControllerImpl.java
  auth/src/main/java/com/fintory/auth/jwt/JwtTokenProvider.java
  auth/src/main/java/com/fintory/auth/service/AuthService.java
  auth/src/main/java/com/fintory/auth/service/AuthServiceImpl.java
  auth/src/main/java/com/fintory/auth/service/CustomUserDetailsService.java
  auth/src/main/java/com/fintory/auth/service/GoogleOauthService.java
  auth/src/main/java/com/fintory/auth/service/KakaoOauthService.java
  auth/src/main/java/com/fintory/auth/service/authservice/ParentAuthServiceImpl.java
  auth/src/main/java/com/fintory/auth/service/socialuserservice/parentOAuth/ParentGoogleOauthService.java
  auth/src/main/java/com/fintory/auth/service/socialuserservice/parentOAuth/ParentKakaoOauthService.java
  compose.yml
  domain/src/main/java/com/fintory/domain/challenge/model/Challenge.java
  domain/src/main/java/com/fintory/domain/child/model/Child.java
  domain/src/main/java/com/fintory/domain/mapping/MappingStatus.java
  domain/src/main/java/com/fintory/domain/mapping/ParentChildMapping.java
  domain/src/main/java/com/fintory/domain/parent/model/Parent.java
  domain/src/main/java/com/fintory/domain/parent/model/ParentRole.java
  infra/src/main/java/com/fintory/infra/domain/parent/repository/ParentRepository.java
  settings.gradle
Labels: chore

#56 fix : deploy.yml에 openAI 키 추가
  app-child/src/main/resources/application-deploy.yml
Labels: bug

#57 fix : 웹소켓 연결하자마자 stock_price_history 저장되도록 수정
  infra/src/main/java/com/fintory/infra/domain/stock/service/websocket/LiveStockPriceWebsocketServiceImpl.java
Labels: refactor

#65 [FEAT] 주식 매매 계좌 내역 업데이트 기능
  auth/src/main/java/com/fintory/auth/util/OpenApiList.java
  domain/src/main/java/com/fintory/domain/portfolio/model/OwnedStock.java
  infra/src/main/java/com/fintory/infra/domain/trading/TradingServiceImpl.java
Labels: feature

#68 FIX: 데이터를 새로 저장하는 방식이 아닌 하나의 데이터를 계속 업데이트 하는 방식으로 되어 있어서 수정.
  infra/src/main/java/com/fintory/infra/domain/stock/service/websocket/LiveStockPriceWebsocketServiceImpl.java
Labels: bug

#70 FIX: merge과정에서 들어간 예전 웹소켓 코드 삭제
  infra/src/main/java/com/fintory/infra/config/StockWebSocketHandler.java
  infra/src/main/java/com/fintory/infra/config/WebSocketConfig.java
Labels: bug
